version: "3"

services:
    mariadb:
        image: mariadb
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./database:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            - MARIADB_ROOT_PASSWORD=root 