/* TIPO DE DADOS TEXTO */
TEXT -- UM TEXTO INFINITO
CHAR(255) -- ALOCA O ESPAÇO INTIERO NO BANCO
VARCHAR(255) -- ALOCA O ESPAÇO QUE IRA USAR

/* TIPO DE DADOS NUMERO */
FLOAT -- UM TEXTO INFINITO
INT -- ALOCA O ESPAÇO INTIERO NO BANCO

/* TIPO DE DADOS DATA */
DATE -- YYYY-MM-DD
DATETIME -- YYYY-MM-DD HH:mm:ss
TIME -- HH:mm:ss
TIMESTAMP -- YYYY-MM-DD HH:mm:ss