version: "3.3"

services:
  mariadb:
    image: mariadb:10.2
    ports:
      - 8080:3306
    environment:
      - MYSQL_USER=mariadb
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./database:/var/lib/mysql
      - ./logs:/var/log/mysql
    networks:
      - mariadb-network

  adminer:
    image: adminer
    ports:
      - 8081:8080
    networks:
      - mariadb-network

networks:
  mariadb-network:
    driver: bridge
