version: "3"

services:
    mongodb_container:
        image: mongo:3.6
        environment:
            MONGO_INITDB_ROOT_USERNAME: ""
            MONGO_INITDB_ROOT_PASSWORD: ""
        ports:
            - 27017:27017
        volumes:
            - ./.mongodb:/data/db