INSERT INTO
  clientes (nome)
VALUES
  ('Júlia'),
  ('Margarida'),
  ('Fabrício'),
  ('César'),
  ('João Miguel'),
  ('Suélen'),
  ('Carlos'),
  ('Maria Eduarda'),
  ('Luiza'),
  ('Hugo'),
  ('Ígor'),
  ('Anthony'),
  ('Lorena'),
  ('Noah'),
  ('Maria Eduarda'),
  ('Célia'),
  ('Manuela'),
  ('Bryan'),
  ('Anthony'),
  ('Théo'),
  ('Hugo'),
  ('Valentina'),
  ('Emanuelly'),
  ('Beatriz'),
  ('Júlio'),
  ('Paulo'),
  ('Vitor'),
  ('Cauã'),
  ('Salvador'),
  ('Felícia'),
  ('Pablo'),
  ('Valentina'),
  ('César'),
  ('Washington'),
  ('Noah'),
  ('Melissa'),
  ('João Pedro'),
  ('Yuri'),
  ('Sílvia'),
  ('Vitória'),
  ('Maria'),
  ('Eduardo'),
  ('Mércia'),
  ('Ricardo'),
  ('Maria'),
  ('Yango'),
  ('Alícia'),
  ('Lucas'),
  ('Félix'),
  ('Raul'),
  ('Felícia'),
  ('Bruna'),
  ('Daniel'),
  ('Suélen'),
  ('Sara'),
  ('Víctor'),
  ('Emanuel'),
  ('Aline'),
  ('Lorena'),
  ('Víctor'),
  ('Maria'),
  ('Alessandra'),
  ('Isabella'),
  ('Laura'),
  ('Raul'),
  ('Miguel'),
  ('Mariana'),
  ('Felipe'),
  ('Carla'),
  ('Morgana'),
  ('Marcos'),
  ('Alessandra'),
  ('Karla'),
  ('Célia'),
  ('Elísio'),
  ('Frederico'),
  ('Helena'),
  ('Luiza'),
  ('Morgana'),
  ('Kléber'),
  ('Lorraine'),
  ('Mércia'),
  ('Lorraine'),
  ('Vitor'),
  ('Ana Luiza'),
  ('Warley'),
  ('Gael'),
  ('João Pedro'),
  ('Ana Luiza'),
  ('Valentina'),
  ('Yuri'),
  ('Ana Luiza'),
  ('Lívia'),
  ('Rebeca'),
  ('Calebe'),
  ('Roberto'),
  ('Júlia'),
  ('Pedro Henrique'),
  ('Lucas'),
  ('Frederico');