SELECT NOME, CODIGO_MALOTE, DESCRICAO, SITUACAO_MALOTE 
FROM MALOTES 
    INNER JOIN CONTEUDOS 
        ON (CODIGO_CONTEUDO = CODIGO_CONTEUDO) 
    INNER JOIN FUNCIONARIOS 
        ON (MATRICULA = MATRICULA);

SELECT NOME, CODIGO_MALOTE, DESCRICAO, SITUACAO_MALOTE 
FROM MALOTES, CONTEUDOS, FUNCIONARIOS 
WHERE (CODIGO_CONTEUDO = CODIGO_CONTEUDO) AND (MATRICULA = MATRICULA);

SELECT NOME, CODIGO_MALOTE, DESCRICAO, SITUACAO_MALOTE 
FROM MALOTES 
    INNER JOIN CONTEUDOS 
    INNER JOIN FUNCIONARIOS 
        ON(MALOTES.CODIGO_CONTEUDO = CONTEUDOS.CODIGO_CONTEUDO) 
        ON(MALOTES.MATRICULA = FUNCIONARIOS.MATRICULA);

[X]
SELECT NOME, CODIGO_MALOTE, DESCRICAO, SITUACAO_MALOTE 
FROM MALOTES 
    INNER JOIN CONTEUDOS
        ON (MALOTES.CODIGO_CONTEUDO = CONTEUDOS.CODIGO_CONTEUDO) 
    INNER JOIN FUNCIONARIOS 
        ON(MALOTES.MATRICULA = FUNCIONARIOS.MATRICULA);