export const DATATYPE = [
  {
    group: "address",
    values: [
      "zipCode",
      "zipCodeByState",
      "city",
      "cityPrefix",
      "citySuffix",
      "cityName",
      "streetName",
      "streetAddress",
      "streetSuffix",
      "streetPrefix",
      "secondaryAddress",
      "county",
      "country",
      "countryCode",
      "state",
      "stateAbbr",
      "latitude",
      "longitude",
      "direction",
      "cardinalDirection",
      "ordinalDirection",
      "nearbyGPSCoordinate",
      "timeZone",
    ],
  },
  {
    group: "animal",
    values: [
      "dog",
      "cat",
      "snake",
      "bear",
      "lion",
      "cetacean",
      "horse",
      "bird",
      "cow",
      "fish",
      "crocodilia",
      "insect",
      "rabbit",
      "type",
    ],
  },
  {
    group: "commerce",
    values: [
      "color",
      "department",
      "productName",
      "price",
      "productAdjective",
      "productMaterial",
      "product",
      "productDescription",
    ],
  },
  {
    group: "company",
    values: [
      "suffixes",
      "companyName",
      "companySuffix",
      "catchPhrase",
      "bs",
      "catchPhraseAdjective",
      "catchPhraseDescriptor",
      "catchPhraseNoun",
      "bsAdjective",
      "bsBuzz",
      "bsNoun",
    ],
  },
  {
    group: "database",
    values: ["column", "type", "collation", "engine"],
  },
  {
    group: "datatype",
    values: [
      "number",
      "float",
      "datetime",
      "string",
      "uuid",
      "boolean",
      "hexaDecimal",
      "json",
      "array",
    ],
  },
  {
    group: "date",
    values: [
      "past",
      "future",
      "between",
      "betweens",
      "recent",
      "soon",
      "month",
      "weekday",
    ],
  },
  {
    group: "finance",
    values: [
      "account",
      "accountName",
      "routingNumber",
      "mask",
      "amount",
      "transactionType",
      "currencyCode",
      "currencyName",
      "currencySymbol",
      "bitcoinAddress",
      "litecoinAddress",
      "creditCardNumber",
      "creditCardCVV",
      "ethereumAddress",
      "iban",
      "bic",
      "transactionDescription",
    ],
  },
  {
    group: "git",
    values: ["branch", "commitEntry", "commitMessage", "commitSha", "shortSha"],
  },
  {
    group: "hacker",
    values: ["abbreviation", "adjective", "noun", "verb", "ingverb", "phrase"],
  },
  {
    group: "helpers",
    values: [
      "randomize",
      "slugify",
      "replaceSymbolWithNumber",
      "replaceSymbols",
      "replaceCreditCardSymbols",
      "repeatString",
      "regexpStyleStringParse",
      "shuffle",
      "mustache",
      "createCard",
      "contextualCard",
      "userCard",
      "createTransaction",
    ],
  },
  {
    group: "image",
    values: [
      "image",
      "avatar",
      "imageUrl",
      "abstract",
      "animals",
      "business",
      "cats",
      "city",
      "food",
      "nightlife",
      "fashion",
      "people",
      "nature",
      "sports",
      "technics",
      "transport",
      "dataUri",
      "lorempixel",
      "unsplash",
      "lorempicsum",
    ],
  },
  {
    group: "internet",
    values: [
      "avatar",
      "email",
      "exampleEmail",
      "userName",
      "protocol",
      "httpMethod",
      "url",
      "domainName",
      "domainSuffix",
      "domainWord",
      "ip",
      "ipv6",
      "port",
      "userAgent",
      "color",
      "mac",
      "password",
    ],
  },
  {
    group: "lorem",
    values: [
      "word",
      "words",
      "sentence",
      "slug",
      "sentences",
      "paragraph",
      "paragraphs",
      "text",
      "lines",
    ],
  },
  {
    group: "mersenne",
    values: ["rand", "seed", "seed_array"],
  },
  {
    group: "music",
    values: ["genre"],
  },
  {
    group: "name",
    values: [
      "firstName",
      "lastName",
      "middleName",
      "findName",
      "jobTitle",
      "gender",
      "prefix",
      "suffix",
      "title",
      "jobDescriptor",
      "jobArea",
      "jobType",
    ],
  },
  {
    group: "phone",
    values: ["phoneNumber", "phoneNumberFormat", "phoneFormats"],
  },
  {
    group: "random",
    values: [
      "number",
      "float",
      "arrayElement",
      "arrayElements",
      "objectElement",
      "uuid",
      "boolean",
      "word",
      "words",
      "image",
      "locale",
      "alpha",
      "alphaNumeric",
      "hexaDecimal",
    ],
  },
  {
    group: "system",
    values: [
      "fileName",
      "commonFileName",
      "mimeType",
      "commonFileType",
      "commonFileExt",
      "fileType",
      "fileExt",
      "directoryPath",
      "filePath",
      "semver",
    ],
  },
  {
    group: "time",
    values: ["recent"],
  },
  {
    group: "vehicle",
    values: [
      "vehicle",
      "manufacturer",
      "model",
      "type",
      "fuel",
      "vin",
      "color",
      "vrm",
      "bicycle",
    ],
  },
];
