version: "3"

services:
    postgres:
        image: "postgres"
        volumes:
            - "./database:/data/postgres"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: "root"
