version: "3"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER="postgres"
      - POSTGRES_PASSWORD="root"
      - POSTGRES_DB="data_test"
    ports:
      - 8080:5432
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./logs:/var/log/postgresql
    networks:
      - postgres-network

  adminer:
    image: adminer
    ports:
      - 8081:8080
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
