version: "3.3"

services:
  mysql8.0:
    image: mysql:8.0
    ports:
      - 8080:3306
    environment:
      - MYSQL_USER="mysql"
      - MYSQL_PASSWORD="root"
      - MYSQL_ROOT_PASSWORD="root"
    volumes:
      - ./database:/var/lib/mysql
      - ./logs:/var/log/mysql
    networks:
      - mysql-network

  adminer:
    image: adminer
    ports:
      - 8081:8080
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge
